### ISSUE TITLE
JOSS review

### ISSUE THREAD

**Issue by pratikvn** [jacobmerson/model-traits#5]
Hello,

I am a reviewer for the [JOSS paper](https://github.com/openjournals/joss-reviews/issues/3389) and will use this issue to track my review and provide some suggestions.

### Installation
+ [x] Spack install
+ [x] Source install

#### IO Backends:
+ [x] YAML
+ [ ] Simmetrix

#### Examples usage
+ [x] Basic example
+ [x] Core example
+ [ ] Example with PUMI
+ [x] Example with YAML

**Comment by pratikvn** [comment]
The software and the code mostly looks good to me. This library is well-written and I believe will be useful to many. 

Some issues I faced and some suggestions:

1. I am not sure how to verify the Simmetrix related functionality.
2. There is no pumi.yaml and related pumi mesh file for the pumi example. I think it would be useful to add these to the inputs folder.
3. I think it is a good idea to copy over the `inputs/` folder from the source `examples/` directory to the `build/` folder, so that it is easier to run the examples with the inputs.
4. `basic_usage.cc` and `core_usage.cc` have inline comments explaining these usage. `pumi.cc` and `yaml_with_backend.cc` lack these comments and I think it would be useful to the users to have this kind of inline comments, especially in the examples.
5. You mostly have done the heavy-lifting with respect to adding the tests and examples and so on. I think it would be very useful to add a CI step to make sure the tests and examples are running as expected. [I tried to add a basic step here and you can use that as a starting point, if you like](https://github.com/pratikvn/model-traits/runs/3270712705).

**Comment by jacobmerson** [comment]
Thanks for taking a look at this and setting up the basic CI! 

Unfortunately the Simmetrix libraries are proprietary. We briefly discussed the issue in the [JOSS pre-review](https://github.com/openjournals/joss-reviews/issues/3307#issuecomment-859726441) and my understanding is that the editor @diehlpk is OK with leaving the Simmetrix bits out of the review since it's not a required component. I'd like to leave the Simmetrix reader in the main model-traits repo since most of my coworkers at RPI use the Simmetrix utilities to set up their models.

I'm in the process of addressing your other concerns.

**Comment by jacobmerson** [comment]
@pratikvn I believe that I have addressed all of the points that you have brought up.

**Comment by pratikvn** [comment]
> Unfortunately the Simmetrix libraries are proprietary. We briefly discussed the issue in the JOSS pre-review and my understanding is that the editor @diehlpk is OK with leaving the Simmetrix bits out of the review since it's not a required component. I'd like to leave the Simmetrix reader in the main model-traits repo since most of my coworkers at RPI use the Simmetrix utilities to set up their models.

I see. Okay, I will then leave that out. Thanks for the information.

Thanks for addressing my concerns and adding a CI job. Everything looks good from my side and hence I will close this issue.
